name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: isOdd Test
      id: isodd-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: isOdd Test
        setup-command: ''
        command: python3 test_main.py
        timeout: 2
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ISODD-TEST_RESULTS: "${{steps.isodd-test.outputs.result}}"
      with:
        runners: isodd-test
